// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = (import.meta.env.VITE_SUPABASE_URL || '').trim();
const SUPABASE_PUBLISHABLE_KEY = (import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || '').trim();

// Validate environment variables - apenas em desenvolvimento
if (import.meta.env.DEV) {
  if (!SUPABASE_URL) {
    console.warn('⚠️ Missing env.VITE_SUPABASE_URL - A aplicação pode não funcionar corretamente');
  }

  if (!SUPABASE_PUBLISHABLE_KEY) {
    console.warn('⚠️ Missing env.VITE_SUPABASE_PUBLISHABLE_KEY - A aplicação pode não funcionar corretamente');
  }
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Criar cliente apenas se as variáveis estiverem definidas
export const supabase = SUPABASE_URL && SUPABASE_PUBLISHABLE_KEY
  ? createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
    }
  })
  : createClient<Database>('https://placeholder.supabase.co', 'placeholder-key', {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
    }
  }); // Cliente placeholder para evitar erros

// Test connection on initialization (optional - can be removed in production)
if (import.meta.env.DEV && SUPABASE_URL && SUPABASE_PUBLISHABLE_KEY) {
  (async () => {
    try {
      const { error } = await supabase
        .from('profiles')
        .select('count')
        .limit(1);
      if (error) {
        console.warn('Supabase connection warning:', error.message);
      } else {
        console.log('✅ Conexão com o banco de dados Supabase estabelecida com sucesso!');
      }
    } catch (err) {
      console.error('❌ Erro ao conectar com o banco de dados:', err);
    }
  })();
}