// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Fallback hardcoded credentials to ensure it works even if Vercel env vars fail
const SUPABASE_URL = (import.meta.env.VITE_SUPABASE_URL || 'https://adrnoeqpbhhecftkmtdh.supabase.co').trim();
const SUPABASE_PUBLISHABLE_KEY = (import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFkcm5vZXFwYmhoZWNmdGttdGRoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjUzNzk5NzQsImV4cCI6MjA4MDk1NTk3NH0.Bl9kE-8J5CE1aQ69OyM-9JDjQBDKSqxAsiGL978zgxA').trim();

// Validate environment variables - apenas em desenvolvimento
if (import.meta.env.DEV) {
  if (!SUPABASE_URL) {
    console.warn('⚠️ Missing env.VITE_SUPABASE_URL - A aplicação pode não funcionar corretamente');
  }

  if (!SUPABASE_PUBLISHABLE_KEY) {
    console.warn('⚠️ Missing env.VITE_SUPABASE_PUBLISHABLE_KEY - A aplicação pode não funcionar corretamente');
  }
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Criar cliente
export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});

// Test connection on initialization (optional - can be removed in production)
if (import.meta.env.DEV && SUPABASE_URL && SUPABASE_PUBLISHABLE_KEY) {
  (async () => {
    try {
      const { error } = await supabase
        .from('profiles')
        .select('count')
        .limit(1);
      if (error) {
        console.warn('Supabase connection warning:', error.message);
      } else {
        console.log('✅ Conexão com o banco de dados Supabase estabelecida com sucesso!');
      }
    } catch (err) {
      console.error('❌ Erro ao conectar com o banco de dados:', err);
    }
  })();
}